name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: actions/setup-node@v1.2.0
      with:
        node-version: '12.x'
    - name: npm install, lint and test
      run: |
        npm ci
        npm run bootstrap
        npm run lint
        npm test
      env:
        CI: true
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: actions/setup-node@v1.2.0
      with:
        node-version: '12.x'
    - name: npm install and build:storybook
      run: |
        npm ci
        npm run bootstrap
        npm run build:storybook
      env:
        CI: true
    - uses: w9jds/firebase-action@v1.2.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
